// frontend-despesas/src/components/login/login.jsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { icon } from '@fortawesome/fontawesome-svg-core/import.macro'
import React, { useState } from 'react'
import { useSelector } from 'react-redux'
import { useForm } from 'react-hook-form'
import './login.css'
import { login } from '../../config/http'
import { useNavigate } from 'react-router-dom'

const setEye = () => {
  let password = document.getElementById('password')
  let eye = document.querySelector('.eye')
  let eyeSlash = document.querySelector('.eye-slash')

  if (password.type === 'password') {
    password.type = 'text'
    eye.setAttribute('style', 'visibility: visible')
    eyeSlash.setAttribute('style', 'visibility: hidden')
  } else {
    password.type = 'password'
    eyeSlash.setAttribute('style', 'visibility: visible')
    eye.setAttribute('style', 'visibility: hidden')
  }
}
const Login = () => {
  const { register, handleSubmit } = useForm()
  const navigate = useNavigate()

  const handleLogin = async (data) => {
    const isLogged = await login(data.email, data.password)

    if (isLogged) {
      navigate('/home')
    }
  }

  return (
    <>
      <div className="main_login">
        <div className="container_login">
          <form className="login-form">
            <div className="row">
              <div className="col-lg-12">
                <h1 className="text-center">Login</h1>
                <input
                  type="text"
                  {...register('email')}
                  id="email"
                  placeholder="insira seu email"
                  className="form-control mt-4"
                />

                <input
                  type="password"
                  {...register('password')}
                  id="password"
                  placeholder="insira sua senha"
                  className="form-control mt-1"
                />
                <label>
                  <FontAwesomeIcon
                    onClick={() => setEye()}
                    className="icon_eye"
                    icon={icon({ name: 'eye', style: 'solid' })}
                  />
                  <FontAwesomeIcon
                    onClick={() => setEye()}
                    className="icon_eye_slash"
                    icon={icon({ name: 'eye-slash', style: 'solid' })}
                  />
                </label>

                {/* <fa-icon class="icon" (click)="set()" *ngIf="!iconOf" [icon]="faEyeSlash"></fa-icon> */}

                <button
                  className="btn btn-outline-secondary mt-4 w-100"
                  onClick={(e) => {
                    e.preventDefault()
                    handleSubmit(handleLogin)()
                  }}
                >
                  Entrar
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </>
  )
}

export default Login

// front-despesas/src/app/login/login.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { faEye, faEyeSlash } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  @ViewChild('passwordInput') passwordInput!: ElementRef;
  faEye = faEye;
  faEyeSlash = faEyeSlash;
  iconOf: boolean = true;

  set(): void {
    this.iconOf = !this.iconOf;
    this.iconOf
      ? (this.passwordInput.nativeElement.type = 'text')
      : (this.passwordInput.nativeElement.type = 'password');
  }
}

<body>
  <div class="container">
  <form class="login-form">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="text-center">Login</h1>
        <input type="text" placeholder="insira seu email" class="form-control mt-4">

        <input #passwordInput type="text" placeholder="insira sua senha" class="form-control mt-1" />
        <fa-icon class="icon" (click)="set()" *ngIf="iconOf" [icon]="faEye"></fa-icon>
        <fa-icon class="icon" (click)="set()" *ngIf="!iconOf" [icon]="faEyeSlash"></fa-icon>

        <button class="btn btn-outline-secondary mt-4 w-100">Entrar</button>
      </div>
    </div>
  </form>
  </div>
</body>
