// front-despesas/src/app/login/login.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { faEye, faEyeSlash } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  @ViewChild('passwordInput') passwordInput!: ElementRef;
  faEye = faEye;
  faEyeSlash = faEyeSlash;
  iconOf: boolean = true;

  set(): void {
    this.iconOf = !this.iconOf;
    this.iconOf
      ? (this.passwordInput.nativeElement.type = 'text')
      : (this.passwordInput.nativeElement.type = 'password');
  }
}

<body>
  <div class="container">
  <form class="login-form">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="text-center">Login</h1>
        <input type="text" placeholder="insira seu email" class="form-control mt-4">

        <input #passwordInput type="text" placeholder="insira sua senha" class="form-control mt-1" />
        <fa-icon class="icon" (click)="set()" *ngIf="iconOf" [icon]="faEye"></fa-icon>
        <fa-icon class="icon" (click)="set()" *ngIf="!iconOf" [icon]="faEyeSlash"></fa-icon>

        <button class="btn btn-outline-secondary mt-4 w-100">Entrar</button>
      </div>
    </div>
  </form>
  </div>
</body>

// front-despesas/src/components/login/login.jsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { icon } from '@fortawesome/fontawesome-svg-core/import.macro'

const Login = () => {
  return (
    <>
      <div
        className="container"
        style={{ background: 'linear-gradient(#6c757d, #a0acb7)' }}
      >
        <form className="login-form">
          <div className="row">
            <div className="col-lg-12">
              <h1 className="text-center">Login</h1>
              <input
                type="text"
                placeholder="insira seu email"
                className="form-control mt-4"
              />

              <input
                type="text"
                placeholder="insira sua senha"
                className="form-control mt-1"
              />

              <FontAwesomeIcon
                className="icon"
                icon={icon({ name: 'eye', style: 'solid' })}
              />
              <FontAwesomeIcon
                className="icon"
                icon={icon({ name: 'eye-slash', style: 'solid' })}
              />
              {/* <fa-icon class="icon" (click)="set()" *ngIf="!iconOf" [icon]="faEyeSlash"></fa-icon> */}

              <button className="btn btn-outline-secondary mt-4 w-100">
                Entrar
              </button>
            </div>
          </div>
        </form>
      </div>
    </>
  )
}

export default Login
