// front-despesas/src/components/home/home.jsx
import './home.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { icon } from '@fortawesome/fontawesome-svg-core/import.macro'

function setBlur(e) {
  let sideMenu = document.querySelector('.side_menu')
  let container = document.querySelector('.container')
  let width = sideMenu.getAttribute('style')

  if (!e) {
    sideMenu.setAttribute('style', 'width: 50px; transition: .2s')
    container.setAttribute('style', 'filter: none')
    width = ''

    return
  }

  e.preventDefault()

  if (width && ~width.indexOf('200px')) {
    sideMenu.setAttribute('style', 'width: 50px; transition: .2s')
    container.setAttribute('style', 'filter: none')
    width = ''
  } else {
    sideMenu.setAttribute('style', 'width: 200px; transition: .2s')
    container.setAttribute('style', 'filter: blur(8px)')
  }
}

//
const Home = () => {
  return (
    <>
      <nav className="mr-4 side_menu">
        <ul className="list">
          <li className="mb-4" onClick={(e) => setBlur(e)}>
            <a>
              <span className="icon ml-2">
                <i className="bi bi-list" />
              </span>
            </a>
          </li>
          <li className="item_menu">
            <a>
              <span className="icon ml-2">
                <i className="bi bi-house-door" />
              </span>
              <span className="txt_link">Home</span>
            </a>
          </li>
          <li className="item_menu">
            <a>
              <span className="icon ml-2">
                <i className="bi bi-speedometer2" />
              </span>
              <span className="txt_link">Dashboard</span>
            </a>
          </li>
          <li className="item_menu">
            <a>
              <span className="icon ml-2">
                <i className="bi bi-box-arrow-left" />
              </span>
              <span className="txt_link">Logout</span>
            </a>
          </li>
        </ul>
      </nav>

      <div className="container" onMouseDown={(e) => setBlur((e = !e))}>
        <h5 className="text-center">Dashboard</h5>
        <div className="row">
          <div className="col-md-4">
            <div className="items mt-2">
              <div className="col-md-6 text-start">
                <label style={{ color: '#ccc6c6', fontSize: 'small' }}>
                  Saldo atual
                </label>
                <span style={{ fontSize: 'medium', fontWeight: 'bold' }}>
                  {'R$ 1000'}
                </span>
              </div>
              <div className="col-md-4 icon">
                <span className="balance_icon">
                  <FontAwesomeIcon
                    icon={icon({
                      name: 'building-columns',
                      style: 'solid'
                    })}
                    color="#fff"
                  />
                </span>
              </div>
            </div>
          </div>

          <div className="col-md-4">
            <div className="items mt-2">
              <div className="col-md-6 text-start">
                <label style={{ color: '#ccc6c6', fontSize: 'small' }}>
                  Receita
                </label>
                <span style={{ fontSize: 'medium', fontWeight: 'bold' }}>
                  {'R$ 20000'}
                </span>
              </div>
              <div className="col-md-4 icon">
                <span className="income_icon">
                  <FontAwesomeIcon
                    icon={icon({ name: 'arrow-up', style: 'solid' })}
                    color="#fff"
                  />
                </span>
              </div>
            </div>
          </div>

          <div className="col-md-4">
            <div className="items mt-2">
              <div className="col-md-6 text-start">
                <label style={{ color: '#ccc6c6', fontSize: 'small' }}>
                  Despesas
                </label>
                <span style={{ fontSize: 'medium', fontWeight: 'bold' }}>
                  {'R$ 10000 '}
                </span>
              </div>
              <div className="col-md-4 icon">
                <span className="expense_icon">
                  <FontAwesomeIcon
                    icon={icon({ name: 'arrow-down', style: 'solid' })}
                    color="#fff"
                  />
                </span>
              </div>
            </div>
          </div>
        </div>

        <div className="row form mt-4">
          <form>
            <div className="col-md-4 mr-1">
              <label className="text-start">Descrição</label>
              <input
                type="text"
                name="description"
                id="description"
                className="form-control"
                style={{ height: '31px', width: '220px' }}
                placeholder="Escreva uma descrição"
              />
              <div className="invalid-feedback">
                Por favor, coloque uma descrição
              </div>
            </div>

            <div className="col-md-4 ml-2">
              <label className="text-start">Valor</label>
              <input
                type="number"
                className="form-control"
                style={{ height: '31px', width: '220px' }}
                placeholder="Escreva um valor"
              />
            </div>

            <div className="col-sm-4 mt-4 ml-2">
              <div>
                <label className="mr-1">
                  <small>Saída</small>
                </label>
                <input type="radio" value="0" name="type" />
              </div>
              <div className="ml-1">
                <label className="mr-1">
                  <small>Entrada</small>
                </label>
                <input type="radio" value="1" name="type" />
              </div>
              <div className="ml-4 d-flex flex-row-reverse">
                <button
                  type="submit"
                  title="Adicionar"
                  className="btn btn-success d-flex justify-content-center"
                >
                  <small>Adicionar</small>
                </button>
              </div>
            </div>
          </form>
        </div>

        <div className="row charts mr-2 mt-4">
          <div className="col-md-12">
            <table>
              <thead>
                <th className="text-start">
                  <small>Descrição</small>
                </th>
                <th className="text-center">
                  <small>Valor</small>
                </th>
                <th className="text-center">
                  <small>Tipo</small>
                </th>
                <th className="text-center">
                  <small>Ações</small>
                </th>
              </thead>
              <hr width="100%" />
              <tbody>
                <td className="text-start">
                  <small>
                    <p>{'descrição'}</p>
                  </small>
                </td>

                <td className="text-center">
                  <small>{'valor'}</small>
                </td>

                <td className="text-center">
                  <FontAwesomeIcon
                    icon={icon({ name: 'arrow-up', style: 'solid' })}
                    color="#1ab424"
                  />
                  <FontAwesomeIcon
                    icon={icon({ name: 'arrow-down', style: 'solid' })}
                    color="#d80808"
                  />
                </td>

                <td className="text-center">
                  <button className="btn-actions">
                    <FontAwesomeIcon
                      icon={icon({ name: 'trash', style: 'solid' })}
                    />
                  </button>
                  <button className="btn-actions ml-4">
                    <FontAwesomeIcon
                      icon={icon({
                        name: 'pen-to-square',
                        style: 'solid'
                      })}
                    />
                  </button>
                </td>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </>
  )
}

export default Home

// front-despesas/src/app/home/home.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import {
  faBuildingColumns,
  faArrowUp,
  faArrowDown,
  faCircleArrowDown,
  faCircleArrowUp,
  faTrash,
  faPenToSquare,
} from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent implements OnInit {
  balance!: number;
  income!: number;
  faBuildingColumns = faBuildingColumns;
  faArrowUp = faArrowUp;
  faArrowDown = faArrowDown;
  faTrash = faTrash;
  faCircleArrowDown = faCircleArrowDown;
  faCircleArrowUp = faCircleArrowUp;
  faPenToSquare = faPenToSquare;
  cont!: any;
  isChecked: boolean = false;
  form!: FormGroup;
  itemsSource: any = [
    {
      description: 'aadddddddddddddddddddddddddddd',
      value: 1000,
      type: true,
    },
    {
      description: 'a',
      value: 2000,
      type: false,
    },
  ];

  constructor(private formBuilder: FormBuilder) {}

  ngOnInit() {
    this.balance = 2000;
    this.income = 20000;
    this.createForm();
  }

  createForm() {
    this.form = this.formBuilder.group({
      description: ['', Validators.required],
      value: ['', Validators.required],
      checks: ['', Validators.required],
    });
  }

  hiddeContainer() {
    this.cont = !this.cont;
  }

  changeCheck() {
    console.log(this.form.value);
  }
}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width-device-width, initial-slace=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
  </head>
<body>

<nav class="side-menu" [ngStyle]="{'width': cont ? '200px' : '50px', 'transition': cont ? '.2s': '.2s'}">

  <ul>
    <li class="btn-expand mb-4" (mousedown)="hiddeContainer()">
      <a>
        <span class="icon">
          <i class="bi bi-list"></i>
        </span>
      </a>
    </li>
    <li class="item-menu">
      <a href="#">
        <span class="icon"><i class="bi bi-house-door"></i></span>
        <span class="txt-link">Home</span>
      </a>
    </li>
    <li class="item-menu">
      <a routerLink="/dashboard">
        <span class="icon"><i class="bi bi-speedometer2"></i></span>
        <span class="txt-link">Dashboard</span>
      </a>
    </li>
    <li class="item-menu">
      <a routerLink="/login">
        <span class="icon"><i class="bi bi-box-arrow-left"></i></span>
        <span class="txt-link">Logout</span>
      </a>
    </li>
  </ul>
</nav>

 <div class="container"  (mousedown)="cont = false" [ngStyle]="{'filter': cont ? 'blur(8px)' : 'none'}">

  <h5 class="text-center">Dashboard</h5>
  <div class="row main-row">

    <div class="mr-2">
      <div class="row items mt-2">
        <div class="col-md-6 text-start">
          <label style="color: #ccc6c6; font-size: small;" translate>Saldo atual</label>
          <span style="font-size: medium; font-weight: bold;">R$ {{balance}}</span>
        </div>
        <div class="col-md-4 icon">
           <span class="balance-icon">
              <fa-icon [icon]="faBuildingColumns" style="color: white;"></fa-icon> <!---  767-->
          </span>
        </div>

      </div>
    </div>

    <div class="mr-2">
      <div class="row items mt-2">
         <div class="col-md-6 text-start">
          <label style="color: #ccc6c6; font-size: small;" translate>Receita</label>
          <span style="font-size: medium; font-weight: bold;">R$ {{income}}</span>
        </div>
        <div class="col-md-4 icon">
          <span class="income-icon">
            <fa-icon [icon]="faArrowUp" style="color: white;"></fa-icon>
          </span>
        </div>
      </div>
    </div>

    <div class="mr-2">
        <div class="row items mt-2">
          <div class="col-md-6 text-start">
           <label style="color: #ccc6c6; font-size: small;" translate>Despesas</label>
           <span style="font-size: medium; font-weight: bold;">R$ {{income}}</span>
         </div>
         <div class="col-md-4 icon">
           <span class="expense-icon">
             <fa-icon [icon]="faArrowDown" style="color: white;"></fa-icon>
           </span>
         </div>
       </div>
    </div>
    <div class="row form mr-2 mt-4">
      <form [formGroup]="form">
        <div class="col-md-4">
          <label>Descrição</label>
          <input type="text" name="description" formControlName="description" class="form-control ng-valid" style="height: 31px;" placeholder="Escreva uma descrição">
        </div>
        <div class="col-md-4">
          <label>Valor</label>
          <input type="number" name="value" formControlName="value" class="form-control" style="height: 31px;" type="number" placeholder="Escreva um valor">
        </div>

        <div class="col-sm-4 mt-4">
          <div>
            <label class="mr-1"><small>Saída</small></label>
            <input formControlName="checks" type="radio" value="0" name="checks" (click)="changeCheck()">
          </div>
          <div class="ml-1">
            <label class="mr-1"><small>Entrada</small></label>
            <input formControlName="checks" type="radio" value="1" name="checks" (click)="changeCheck()">
          </div>

          <div class="ml-3 d-flex flex-row-reverse">
            <button title="Adicionar" class="btn d-flex justify-content-center"><small>Adicionar</small></button>
          </div>
        </div>

      </form>
    </div>

    <div class="row charts mr-2 mt-4">
      <div class="col-md-12">
        <table>
          <thead>
            <th class="text-start"><small>Descrição</small></th>
            <th class="text-center"><small>Valor</small></th>
            <th class="text-center"><small>Tipo</small></th>
            <th class="text-center"><small>Ações</small></th>
          </thead>
          <hr width="100%">
          <tbody *ngFor="let item of itemsSource">
            <td class="text-start">
              <small><p>{{item.description}}</p></small>
            </td>
            <td class="text-center">
              <small>{{item.value}}</small>
            </td>
            <td class="text-center">
              <fa-icon *ngIf="item.type" [icon]="faCircleArrowUp" style="color: #1ab424;"></fa-icon>
              <fa-icon *ngIf="!item.type" [icon]="faCircleArrowDown" style="color: #d80808;"></fa-icon>
            </td>
            <td class="text-center">
              <button style="border: none!important; background-color: white!important;"><fa-icon [icon]="faTrash"></fa-icon></button>
              <button style="border: none!important; background-color: white!important;" class="ml-4"><fa-icon [icon]="faPenToSquare"></fa-icon></button>
            </td>
          </tbody>
        </table>
      </div>

    </div>
  </div>
 </div>
</body>
</html>
